Update allPackages-AutoBuild.yml

diff --git a/.github/workflows/allPackages-AutoBuild.yml b/.github/workflows/allPackages-AutoBuild.yml
--- a/.github/workflows/allPackages-AutoBuild.yml
+++ b/.github/workflows/allPackages-AutoBuild.yml
@@ -179,6 +179,7 @@ jobs:
         cp -rf devices/${{matrix.target}}/. ./
         chmod -R +x devices/* || true
         sed -i '/	refresh_config();/d' scripts/feeds
+        [[ "$(echo "${{github.event.action}}" | grep "pkgs")" ]] || sed -i "/packages/d" feeds.conf.default
         find "devices/common/patches" -type f -name '*.b.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"
         /bin/bash "devices/common/custom2.sh"
         if [ -f "devices/${{matrix.target}}/custom2.sh" ]; then
@@ -206,9 +207,15 @@ jobs:
     - name: Compile the firmware
       run: |
         cd openwrt
+        if [[ "$(echo "${{github.event.action}}" | grep "pkgs")" ]]; then
+          for ipk in $(ls package/feeds/packages/); do
+          (make -k package/$ipk/compile -j$(($(nproc)+1)) || make package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || rm -rf error_$ipk.log) || true
+          done
+        else
           echo -e "$(($(nproc)+1)) thread compile"
-          make -j$(($(nproc)+1)) -k || df -hT
+          make -j$(($(nproc)+1)) -k || true
         echo "status=success" >> $GITHUB_ENV
+        fi
 
     - name: Check space usage
       run: df -hT
